README.rst

Test for committing files

---

README.md
main.py
pynapple/io/wrappers.py
pynapple/process/correlograms.py
pynapple/process/decoding.py
pynapple/process/tuning_curves.py

Reverts PeyracheLab/pynapple#30

Revert "A few edits in the helpers"

---

pynapple/io/loader.py
pynapple/io/neurosuite.py

Reverts PeyracheLab/pynapple#79

Revert "read_neuroscope_intervals function"

---

.github/workflows/main.yml
.gitignore
pyproject.toml
requirements.txt
requirements_dev.txt
setup.cfg
setup.py

This is the version with only the files required for the configuration. Ideally the changes should be applied in subsequent commits on this branch if that is fine with you, otherwise it is tricky to know whether testing is running! (GitHub Actions is already running on my fork, but failing until I apply the lint obviously). But you can also merge this and fix tests in a separate branch!

linting and testing files

---

pynapple/core/ts_group.py

This feature was not added when the old PR was closed

adding metadata columns property to TsGroup

---

docs/examples/tutorial_pynapple_dandi.py

DANDI style

---

docs/examples/tutorial_pynapple_numpy.py
pynapple/core/interval_set.py
pynapple/core/time_index.py
pynapple/core/time_series.py
pynapple/core/ts_group.py
pynapple/io/interface_npz.py

Fixing tsgroup save

---

pynapple/core/ts_group.py
tests/test_npz_file.py
tests/test_ts_group.py

Ts group repr

---

tests/test_lazy_loading.py

Added a "tmp_path" fixture that generates a temporary path before writing, unique to the test invocation.

Fix write issue windows

---

pynapple/core/interval_set.py
tests/test_interval_set.py
tests/test_jitted.py
tests/test_lazy_loading.py
tests/test_misc.py
tests/test_time_series.py
tests/test_ts_group.py

DOes this :
```
ep = nap.IntervalSet(0, 100)
ep.split(interval_size=1)
```
return a new IntervalSet of length 100 with intervals of size 1 second

Iset splitting

---

pynapple/core/_core_functions.py
pynapple/core/_jitted_functions.py
pynapple/core/base_class.py
pynapple/core/time_series.py
pynapple/core/ts_group.py
tests/test_jitted.py
tests/test_time_series.py
tests/test_ts_group.py

Added a dtype argument to count for Ts and TsGroup

Added dtype for count

---

docs/HISTORY.md
pynapple/__init__.py
pyproject.toml
setup.py

bumping 0.7.1

---

pynapple/process/spectrum.py
tests/test_power_spectral_density.py

Adding validators to spectrum.py and overlap option for mean power spectral density

Refactor spectrum

---

.github/workflows/main.yml
docs/api_guide/tutorial_pynapple_core.py
docs/api_guide/tutorial_pynapple_io.py
docs/api_guide/tutorial_pynapple_nwb.py
docs/api_guide/tutorial_pynapple_quick_start.py
docs/gallery_conf.py
docs/index.md
mkdocs.yml
pyproject.toml

Added a CI job that builds the website and checks all the links in the html generated.
In the process, fixed all broken links!

Automate link check

---

.github/workflows/documentation.yml

Adding worflow for automatic building of the documentation

Sphinx doc

---

doc/examples/tutorial_wavelet_decomposition.md
doc/user_guide/10_power_spectral_density.md
doc/user_guide/12_filtering.md
pynapple/process/__init__.py
pynapple/process/spectrum.py
tests/test_power_spectral_density.py

Changing `compute_mean_power_spectral_density` to be the normalized squared of the FFT. The function returns a real-valued pandas DataFrame.

Update mean PSD

---

doc/conf.py
doc/examples.md
doc/examples/tutorial_ibl_choice_decoding.md
pyproject.toml

Hi @gviejo, just following up with that build_tensor demo we had discussed! Let me know if you have any feedback. In particular, am I merging into the right branch? Also, happy to add some more content if you have ideas. Thanks!!

[doc] examples: IBL choice decoding

---

pynapple/core/time_series.py
tests/test_time_series.py

Problem with isinstance 
isinstance(n, int) was not detecting n as a int. Should be isinstance(n, np.integer)

Fix 437 issue

---

doc/releases.md

Bump 0.8.5

---

.github/workflows/main.yml
doc/index.rst
doc/user_guide/03_core_methods.md
pynapple/core/interval_set.py
pynapple/core/metadata_class.py
pynapple/core/time_series.py
pynapple/core/ts_group.py
pynapple/core/utils.py
tests/test_interval_set.py
tests/test_repr.py
tests/test_time_series.py
tests/test_ts_group.py

Small fixes before release

---

pynapple/process/decoding.py
tests/test_decoding.py

Small bug fix in old `decode_1d` function (still there for backward compatibility).

Decoding bug fix

---

pynapple/process/_process_functions.py

Fixing perievent
