docs/process.randomize.md, mkdocs.yml, pynapple/process/__init__.py, pynapple/process/randomize.py, tests/test_perievent.py, tests/test_randomize.py
Dear Guillaume and Pynapple maintainers,
I implemented some randomization procedures for pynapple ts and tsgroup objects, with the idea that they could be useful to compute null distributions for statistical testing.
I tried to follow the contribution guidelines as closely as possible. 
Here is a description of the new functionalities:
I located the routines in process.randomize.py. Currently, there are three types of randomization implemented:
- `shift_timestamps` shifts all the timestamps in a Ts object by a random amount, wrapping the end to the beginning. If applied to a TsGroup, all Ts in the group are independently shifted
- `jitter_timestamps` jitters all the timestamps in a Ts (or TsGroup) of a different random amount, uniformly sampled betw. -max_jitter and max_jitter. By …
=> Added Ts randomization routines

pynapple/process/tuning_curves.py
This code will work the same as before if nb_bins is int, but if a tuple of 2 ints is provided, it will use the corresponding value for each feature separately. Convenient for non-square environments.
=>  Separate nb_bins for two features in 2D tuning curves

docs/HISTORY.md, pynapple/core/base_class.py, pynapple/core/time_series.py, tests/test_time_series.py
`smooth` now takes standard deviation in time units
=> Changing smooth function

pynapple/core/ts_group.py, tests/test_ts_group.py
Modified the `__init__` of the ts_group. Now it coverts all keys to integer with the following behavior:
1. Raises `ValueError` if any of the keys cannot be converted to` int`
2. Raises `ValuError` if the converted key has a different value from the original, for example `{1.2: ts}` is not accepted because 1.2 would be converted to 1. This avoids issue if one has two float keys with the same integer part
3. Rasies `ValueError` if after conversion two keys have the same value. this happens in this weird corner case 
`d={1:ts, "1": ts}`
1. Added initialization test with corner cases.
2. Change the parametrize over the class to fixture, more standard, and doesn't need to be passed if not used.
=> Ts group init

docs/examples/tutorial_pynapple_process.py, pynapple/core/interval_set.py, pynapple/core/time_series.py, pynapple/core/ts_group.py, pynapple/core/utils.py, tests/test_interval_set.py, tests/test_time_series.py
=> Fixing repr

docs/HISTORY.md, pynapple/__init__.py, pynapple/core/time_series.py, pyproject.toml, setup.py
- Improving `__repr__` for all objects.
- TsGroup `__getattr__` and `__setattr__` added to access metadata columns directly
- TsGroup `__setitem__` now allows changes directly to metadata
- TsGroup `__getitem__` returns column of metadata if passed as string
=> Bumping 0.6.3

pynapple/io/misc.py
Should fix #297 
Currently append_NWB_LFP function will not work with TsdFrames; this fixes by casting ndarray to a list - otherwise, the ndarray will reach `nwbfile.create_electrode_table_region` which will error (as it requires slice or list or tuple).
=> Currently append_NWB_LFP function will not work with TsdFrames; this fixes.

pynapple/core/ts_group.py, tests/test_time_series.py, tests/test_ts_group.py
This PR solves the issue of infinite recursion for the pickling of "TsGroup".
Raises an error if `__getattr__` is called by the `__reduce__` and `__reduce_ex__` methods. 
These are attributes of the `pandas.Index`, which are the column names of the metadata, that would be called by captured by the `__getattr__` implementation otherwise, generating an infinite recursion.
This two line now do not generate an infinite recursion.
```python
import pickle
#...assume tsgroup is a TsGroup
pickled_tsgroup = pickle.dumps(tsgroup)
unpickled_tsgroup = pickle.loads(pickled_tsgroup)
```
=> Pickling tsgroup

pynapple/core/base_class.py, pynapple/core/interval_set.py, pynapple/core/time_series.py, pynapple/core/ts_group.py, pynapple/core/utils.py, pynapple/io/cnmfe.py, pynapple/io/folder.py, pynapple/io/interface_npz.py, pynapple/io/interface_nwb.py, pynapple/io/loader.py, pynapple/io/misc.py, pynapple/io/neurosuite.py, pynapple/io/phy.py, pynapple/io/suite2p.py, tests/test_folder.py, tests/test_interval_set.py, tests/test_lazy_loading.py, tests/test_misc.py, tests/test_npz_file.py, tests/test_nwb.py, tests/test_time_series.py, tests/test_ts_group.py
Refactoring that purges the `os` dependency for working with the filesystem in favour of the more modern `pathlib`, as per #299.
Since I was not sure of the temporal horizon of the removal of importing modules I just did the refactoring everywhere. 
I also included a small refactoring to avoid the code duplications in the `save` methods across `Ts`X classes.
=> Os removal

pynapple/core/ts_group.py, tests/test_ts_group.py
It doesn't seem to make a ton of sense to me to require that users manually package their timestamp/series objects into a dict when creating `TsGroup` objects, since the keys are required to be unique integers. I would guess that the vast majority of the time, users would be just doing `{0: ts0, 1: ts1, ...}`. Sure, this can be easily done by saying `data = dict(enumerate(ts_list))`, but why not just allow the user to say `data = ts_list` and do the dict creation automatically?
If the change described above is not desired, the second commit is probably still worth including. It ensures that the keys in `.data` and `.index` are in the same order by doing this:
```
data = {k: data[k] for k in self.index}
```
This might not be assured if `bypass_check == True`.
I added some tests for the new …
=> Create a TsGroup from an iterable of Ts/Tsd objects

pynapple/process/tuning_curves.py
Hello! 
I noticed that in functions such as `compute_1d_mutual_info()` (along with others), when the `minmax` argument is not provided, the bins are made using the minimum and maximum value of the provided feature using functions `np.min()` and `np.max()`. The issue with this, however, is that if there are any nans in the feature, then `np.min()` and `np.max()` will return nan; This results in bins of 'nans', and therefore mutual info values of all zeros. I've had a similar issue with tuning curves. To fix this, I changed the the `np.min()` and `np.max()` functions to `np.nanmin()` and `np.nanmax()` respectively. These functions ignore nans.
=> Fixing nan bug when creating bins from min and max of feature

docs/index.md, pynapple/core/time_series.py, pynapple/process/tuning_curves.py, tests/test_tuning_curves.py
- Fix issue #334.
- Adding `nanmin` and `nanmax` (with help from #330)
- Adding validation method as a decorator for all tuning curves methods. Check type of every arguments collectively.
- Refactor tests for module `tuning_curves.py`.
=> Refactor tuning curves

.github/workflows/main.yml, pynapple/core/time_series.py, tests/test_time_series.py
On TsdFrame of 1 column, this would cause an error:
```python
tsdframe = nap.TsdFrame(t=np.arange(10), d=np.ones((10, 1)))
tsdframe[0]
```
Since in the getitem it was checking if `key[1]` is list or array but key is an integer in this case. 
Fixed it quickly and added a test for this 1 column tsdframe.
=> Bugfix on TsdFrame getitem

pynapple/core/interval_set.py, pynapple/io/interface_nwb.py, tests/test_decoding.py, tests/test_metadata.py
There was an issue with creating IntervalSets from loaded NWB files, where the IntervalSet object was being created first, thus sorting start and end times, and afterwards adding metadata that is now misaligned. This fix changes the load so that metadata is passed at creation in a dataframe with the start and end times, preserving the alignment. 
An initial sort of an input dataframe start times, which preserves their relationship to each end time, is also done in an attempt to preserve the metadata. This is because when start and end times are sorted separately, as they are later in the constructor, metadata is dropped since it is unclear whether to pair metadata with the start or end time. However, if end times need to be sorted later in the constructor, metadata will still be dropped.
=> Fix loading and IntervalSet from NWB file with metadata

pynapple/core/time_series.py, tests/test_time_series.py
Some of the methods of Tsd were not overwriting the epochs when `ep` was provided (like bin_average. or interpolate).
Fix the issue with this PR to fix the behavior of these operation. Added tests.
=> Hotfix - tsd initialization

doc/external.md, pynapple/process/__init__.py, pynapple/process/spectrum.py, tests/test_power_spectral_density.py, tests/test_signal_processing.py
This PR updates the functionality of `compute_power_spectral_density` to actually compute the periodogram, where previously it was only computing the FFT. Additionally, a new function `compute_fft` has been added that contains the old functionality of `compute_power_spectral_density`.
=> Update the definition of `compute_power_spectral_density` to compute the true PSD

pynapple/core/_core_functions.py, pynapple/core/base_class.py, pynapple/core/config.py, pynapple/core/interval_set.py, pynapple/core/time_index.py, pynapple/core/time_series.py, pynapple/core/ts_group.py, pynapple/core/utils.py, pynapple/process/_process_functions.py, pynapple/process/perievent.py, pynapple/process/wavelets.py, tests/test_signal_processing.py
Changes the output of `compute_wavelet_transform` such that, if returning a TsdFrame, the column names correspond to the input frequencies `freqs` (Issue #404)
=> add column names for compute_wavelet_transform

pynapple/core/interval_set.py
The wrong values were getting printed on the bottom rows of the `__repr__` when rows are collapsed from a small terminal size
=> Fix value printing of IntervalSet when rows are collapsed

pynapple/core/interval_set.py, pynapple/core/metadata_class.py, tests/test_metadata.py, tests/test_npz_file.py
addresses issue #407 
fixes indexing of IntervalSet such that indexing like `ep[-1]` or `ep[[0,-1]]` doesn't throw an error
=> fix indexing of IntervalSet to be able to use `-1`

doc/user_guide/03_core_methods.md, pynapple/core/_core_functions.py, pynapple/core/_jitted_functions.py, pynapple/core/base_class.py, pynapple/core/ts_group.py, tests/test_jitted.py, tests/test_time_series.py, tests/test_ts_group.py
This issue adds a modality to `value_from` that allows to choose the values before, after, or closest to the time stamps of a Ts, and should resolve part of #367.
In a subsequent PR, we should add a threshold.
=> Issue 367 value from

doc/user_guide/08_perievent.md
Re-scaled the peth in the example to Hz (spikes/sec), for a more straight forward interpretation
=> chage example to spk/sec

pynapple/core/ts_group.py, tests/test_ts_group.py
When initializing empty TsGroup, the rate attribute was not added to the metadata dataframe.
=> Fix tsgrouprate

.github/workflows/documentation.yml
By default, `actions/checkout` doesn't grab git tags (see https://github.com/pypa/setuptools_scm/issues/480 and https://stackoverflow.com/a/68959339), which means that the version that sphinx was grabbing was wrong. This fixes that.
=> make GHA checkout grab git tags

.github/workflows/deploy.yml
This PR adds a new Github workflow file, `deploy.yml`, which will build and publish release to PyPI whenever you release them through Github. In order to make this work, you'll [need to set up trusted publishing](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/), which involves signing into PyPI and basically giving this github repo permission to upload for you (you'll need to specify the workflow's file name, `deploy.yml`).
In addition to building and deploying, this also checks:
- that we only built a single release
- that its version tag matches the most recent git tag
- that we can install from the wheel
- that the tests pass (right now, this is just `pytest tests/`, you could add other stuff if you like; for plenoptic, I also test that I can run the …
=> Publish workflow

.gitignore, pynapple/core/ts_group.py, tests/test_ts_group.py
This PR modifies the `TsGroup` `count` method to preserve metadata and pass it to the resulting `TsdFrame`. Additionally, it recomputes the "rate" metadata to be specific to the interval over which `count` was called.
I added checks for metadata to two tests in `test_ts_group.py`: `test_count` and `test_count_with_ep`. More generally, I refactored both of these tests to use parametrization to test more intervals and bin sizes, as well as checking the count results against similar numpy functions.
=> Preserve metadata when calling `count` on a `TsGroup`

pynapple/core/ts_group.py, tests/test_ts_group.py
when preserving `TsGroup` metadata using `count`, drop `rate` to minimize crowding and confusion with the existing `rate` attribute of `TsdFrame`
=> drop rate metadata when using count

doc/user_guide/03_core_methods.md, pynapple/core/time_series.py, tests/test_time_series.py
Implements https://github.com/pynapple-org/pynapple/issues/389
* Adds support for a new `derivative` method which wraps `np.gradient` with support for epochs and time index
* Adds unit tests with & without epochs
Update: Added example to user docs:
Let me know what you think!
=> Add gradient method for calculating derivatives

doc/user_guide/12_filtering.md, pynapple/process/filtering.py, tests/test_filtering.py
Adds a new method `detect_oscillatory_events` to the `filtering` module that allows for detection of ripple-like intervals in signals. Based on [this EEG processing example](https://github.com/PeyracheLab/pynacollada/blob/main/pynacollada/eeg_processing/eeg_processing.py). 
* Will follow-up with a new user guide as discussed demonstrating usage on real data
* Still having trouble getting the sphinx docs to consistently compile - believe this is a local dev issue.
* We discussed using `apply_bandpass` instead of `filtfilt` but I think as written, both may be necessary unless we think it's ok to skip the smoothing step—or could use `Tsd.smooth` here?
* Does the testing approach make sense / seem adequate here?
=> Add `detect_oscillatory_events` method
